--
-- PostgreSQL database dump
--

-- Dumped from database version 17.0 (Debian 17.0-1.pgdg120+1)
-- Dumped by pg_dump version 17.0 (Debian 17.0-1.pgdg120+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: universes; Type: TABLE; Schema: public; Owner: user-dev
--

CREATE TABLE public.universes (
	id bigint NOT NULL,
	name character varying(100) NOT NULL,
	launch_file_path character varying(200) NOT NULL,
	ros_version character varying(4) NOT NULL,
	visualization character varying(50) NOT NULL,
	world character varying(50) NOT NULL
);


ALTER TABLE public.universes OWNER TO "user-dev";

--
-- Name: exercises_universe_id_seq; Type: SEQUENCE; Schema: public; Owner: user-dev
--

ALTER TABLE public.universes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
	SEQUENCE NAME public.exercises_universe_id_seq
	START WITH 1
	INCREMENT BY 1
	NO MINVALUE
	NO MAXVALUE
	CACHE 1
);


--
-- Data for Name: universes; Type: TABLE DATA; Schema: public; Owner: user-dev
--

COPY public.universes (id, name, launch_file_path, ros_version, visualization, world) FROM stdin;
1	Vacuums House	/opt/jderobot/Launchers/vacuum_cleaner.launch.py	ROS2	gazebo_rae	gazebo
2	City Large	/opt/jderobot/Launchers/taxi_navigator.launch.py	ROS2	gazebo_rae	gazebo
3	Rescue Default	/opt/jderobot/Launchers/world.json	ROS2	gazebo_rae	drones
4	Warehouse 1	/opt/jderobot/Launchers/amazon_robot.launch.py	ROS2	gazebo_rae	gazebo
5	Simple Circuit	/opt/jderobot/Launchers/simple_circuit.launch.py	ROS2	gazebo_rae	gazebo
6 	Montreal Circuit	/opt/jderobot/Launchers/montreal_circuit.launch.py	ROS2	gazebo_rae	gazebo
7	Follow Person	/opt/jderobot/Launchers/follow_person.launch.py	ROS2	gazebo_rae	gazebo
8	Follow Person Teleop	/opt/jderobot/Launchers/follow_person_teleop.launch.py	ROS2	gazebo_rae	gazebo
9	Autoparking Simple: In line	/opt/jderobot/Launchers/prius_autoparking.launch.py	ROS2	gazebo_rae	gazebo
10	Obstacle Avoidance Default	/opt/jderobot/Launchers/simple_circuit_obstacles_followingcam.launch.py	ROS2	gazebo_rae	gazebo
11 	City Large Followcam	/opt/jderobot/Launchers/taxi_navigator_followingcam.launch.py	ROS2	gazebo_rae	gazebo
12 	3d Reconstruction	/opt/jderobot/Launchers/3d_reconstruction.launch.py	ROS2	gazebo_rae	gazebo
13 	Autoparking Simple: In battery	/opt/jderobot/Launchers/prius_bateria.launch.py	ROS2	gazebo_rae	gazebo
14 	Autoparking Gas Station: In line	/opt/jderobot/Launchers/gas_station_line_ackermann.launch.py	ROS2	gazebo_rae	gazebo
15 	Autoparking Gas Station: In battery	/opt/jderobot/Launchers/gas_station_battery_ackermann.launch.py	ROS2	gazebo_rae	gazebo
16 	Autoparking Gas Station: Parking lot	/opt/jderobot/Launchers/gas_station_parking_ackermann.launch.py	ROS2	gazebo_rae	gazebo
17 	Warehouse 1 Ackermann	/opt/jderobot/Launchers/small_warehouse_with_ackermann_logistic_robot.launch.py	ROS2	gazebo_rae	gazebo
18 	Warehouse 2 Ackermann	/opt/jderobot/Launchers/pallet_warehouse_with_ackermann_logistic_robot.launch.py	ROS2	gazebo_rae	gazebo
19 	Warehouse 2	/opt/jderobot/Launchers/pallet_warehouse.launch.py	ROS2	gazebo_rae	gazebo
20 	Montmelo Circuit	/opt/jderobot/Launchers/montmelo_circuit.launch.py	ROS2	gazebo_rae	gazebo
21 	Nurburgring Circuit	/opt/jderobot/Launchers/nurburgring_circuit.launch.py	ROS2	gazebo_rae	gazebo
22 	Nurburgring Ackermann Circuit	/opt/jderobot/Launchers/nurburgring_circuit_ackermann.launch.py	ROS2	gazebo_rae	gazebo
23 	Montmelo Ackermann Circuit	/opt/jderobot/Launchers/montmelo_circuit_ackermann.launch.py	ROS2	gazebo_rae	gazebo
24 	Montreal Ackermann Circuit	/opt/jderobot/Launchers/montreal_circuit_ackermann.launch.py	ROS2	gazebo_rae	gazebo
25 	Simple Ackermann Circuit	/opt/jderobot/Launchers/simple_circuit_ackermann.launch.py	ROS2	gazebo_rae	gazebo
26	Autoparking Lidar Simple: In line	/opt/jderobot/Launchers/prius_360_autoparking.launch.py	ROS2	gazebo_rae	gazebo
27	Vacuums House Roof	/opt/jderobot/Launchers/montecarlo_visual_loc.launch.py	ROS2	gazebo_rae	gazebo
\.


--
-- Name: exercises_universe_id_seq; Type: SEQUENCE SET; Schema: public; Owner: user-dev
--

SELECT pg_catalog.setval('public.exercises_universe_id_seq', 1, false);


--
-- Name: universes exercises_universes_name_key; Type: CONSTRAINT; Schema: public; Owner: user-dev
--

ALTER TABLE ONLY public.universes
	ADD CONSTRAINT exercises_universes_name_key UNIQUE (name);


--
-- Name: universes universes_pkey; Type: CONSTRAINT; Schema: public; Owner: user-dev
--

ALTER TABLE ONLY public.universes
	ADD CONSTRAINT universes_pkey PRIMARY KEY (id);


--
-- Name: exercises_universe_name_459df99a_like; Type: INDEX; Schema: public; Owner: user-dev
--

CREATE INDEX exercises_universe_name_459df99a_like ON public.universes USING btree (name varchar_pattern_ops);


--
-- PostgreSQL database dump complete
--

